INSERT INTO autores (nome, nacionalidade) VALUES
    ('Machado de Assis', 'Brasileira'),
    ('Clarice Lispector', 'Brasileira'),
    ('George Orwell', 'Britânica'),
    ('J.K. Rowling', 'Britânica'),
    ('Stephen King', 'Americana'),
    ('Gabriel García Márquez', 'Colombiana'),
    ('J.R.R. Tolkien', 'Britânica'),
    ('Agatha Christie', 'Britânica'),
    ('Jorge Amado', 'Brasileira'),
    ('Virginia Woolf', 'Britânica'),
    ('Ernest Hemingway', 'Americana'),
    ('Haruki Murakami', 'Japonesa'),
    ('Isabel Allende', 'Chilena'),
    ('Carlos Drummond de Andrade', 'Brasileira'),
    ('Franz Kafka', 'Tcheca');