//@no-log
POST http://localhost:3000/products
Content-Type: application/json
Accept: application/json

{
  "nome": "Controle sem fio para xbox series s",
  "descricao": "Anatômico",
  "preco": 349,
  "estoque": 19,
  "categoryId": 3
}

###

//@no-log
GET http://localhost:3000/products
Content-Type: application/json
Accept: application/json

###

//@no-log
GET http://localhost:3000/products/10
Content-Type: application/json
Accept: application/json

###

//@no-log
PUT http://localhost:3000/products/2
Content-Type: application/json
Accept: application/json

{
  "preco": 0.01
}

###

//@no-log
DELETE http://localhost:3000/products/7
Content-Type: application/json
Accept: application/json

###

//@no-log
POST http://localhost:3000/products/find-by-name
Content-Type: application/json
Accept: application/json

{
"nome": "notebook"
}

###

//@no-log
GET http://localhost:3000/products/stock/available
Content-Type: application/json
Accept: application/json

###

//@no-log
GET http://localhost:3000/products/stock/empty
Content-Type: application/json
Accept: application/json

###

//@no-log
GET http://localhost:3000/products/filter?minPrice=900&maxPrice=2500
Content-Type: application/json
Accept: application/json
