###
// @no-log # desativa salvar arquico
GET http://localhost:3000/api/v1/produtos
Accept: application/json
###
// @no-log # desativa salvar arquico
GET http://localhost:3000/api/v1/produtos?nome=mec
Accept: application/json
###
// @no-log # desativa salvar arquico
GET http://localhost:3000/api/v1/produtos/1
###
// @no-log # desativa salvar arquico
GET localhost:3000/health-check
###
// @no-log # desativa salvar arquico
POST localhost:3000/api/v1/produtos
Content-Type: application/json
Accept: application/json

{
  "nome": "Notebook 14'",
  "preco": 3999.98,
  "estoque": 4
}

###
// @no-log # desativa salvar arquico
PATCH localhost:3000/api/v1/produtos/3
Content-Type: application/json
Accept: application/json

//  "nome": "Notebook 14' Dell"
#"ativo": true
{
    "estoque": 6,
    "preco": 2500.97
}

###
// @no-log # desativa salvar arquico
DELETE localhost:3000/api/v1/produtos/99
